config/routes.rb
Rails.application.routes.draw do
  resources :constituents
  resources :events
 
  root 'events#index'
 

end

app/models/constituent.rb
class Constituent < ActiveRecord::Base
    def no_of_constituents
        Constituent.count 
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/constituents_controller.rb
class ConstituentsController < ApplicationController
  before_action :set_constituent, only: [:show, :edit, :update, :destroy]

  # GET /constituents
  # GET /constituents.json
  def index
    @constituents = Constituent.all
  end

  # GET /constituents/1
  # GET /constituents/1.json
  def show
  end

  # GET /constituents/new
  def new
    @constituent = Constituent.new
  end

  # GET /constituents/1/edit
  def edit
  end

  # POST /constituents
  # POST /constituents.json
  def create
    @constituent = Constituent.new(constituent_params)

    respond_to do |format|
      if @constituent.save
        format.html { redirect_to @constituent, notice: 'Constituent was successfully created.' }
        format.json { render :show, status: :created, location: @constituent }
      else
        format.html { render :new }
        format.json { render json: @constituent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /constituents/1
  # PATCH/PUT /constituents/1.json
  def update
    respond_to do |format|
      if @constituent.update(constituent_params)
        format.html { redirect_to @constituent, notice: 'Constituent was successfully updated.' }
        format.json { render :show, status: :ok, location: @constituent }
      else
        format.html { render :edit }
        format.json { render json: @constituent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /constituents/1
  # DELETE /constituents/1.json
  def destroy
    @constituent.destroy
    respond_to do |format|
      format.html { redirect_to constituents_url, notice: 'Constituent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_constituent
      @constituent = Constituent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def constituent_params
      params.require(:constituent).permit(:first_name, :last_name, :title, :district, :email, :phone_number)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :place, :time, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/constituents_helper.rb
module ConstituentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/constituents/_form.html.erb
<%= form_for(@constituent) do |f| %>
  <% if @constituent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@constituent.errors.count, "error") %> prohibited this constituent from being saved:</h2>

      <ul>
      <% @constituent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :district %><br>
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/constituents/edit.html.erb
<h1>Editing Constituent</h1>

<%= render 'form' %>

<%= link_to 'Show', @constituent %> |
<%= link_to 'Back', constituents_path %>

app/views/constituents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Constituents</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Title</th>
      <th>District</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @constituents.each do |constituent| %>
      <tr>
        <td><%= constituent.first_name %></td>
        <td><%= constituent.last_name %></td>
        <td><%= constituent.title %></td>
        <td><%= constituent.district %></td>
        <td><%= constituent.email %></td>
        <td><%= constituent.phone_number %></td>
        <td><%= link_to 'Show', constituent %></td>
        <td><%= link_to 'Edit', edit_constituent_path(constituent) %></td>
        <td><%= link_to 'Destroy', constituent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Constituent', new_constituent_path %>

app/views/constituents/new.html.erb
<h1>New Constituent</h1>

<%= render 'form' %>

<%= link_to 'Back', constituents_path %>

app/views/constituents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @constituent.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @constituent.last_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @constituent.title %>
</p>

<p>
  <strong>District:</strong>
  <%= @constituent.district %>
</p>

<p>
  <strong>Email:</strong>
  <%= @constituent.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @constituent.phone_number %>
</p>

<%= link_to 'Edit', edit_constituent_path(@constituent) %> |
<%= link_to 'Back', constituents_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Place</th>
      <th>Time</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.place %></td>
        <td><%= event.time %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Place:</strong>
  <%= @event.place %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>